#!/bin/sh

set -euo pipefail

css=internal/www/public/styles/index.css
sum=$(cat $css | shasum -a 256 | cut -d' ' -f1)
mv $css internal/www/public/styles/index.$sum.css

js=internal/www/public/scripts/app.js
sum=$(cat $js | shasum -a 256 | cut -d' ' -f1)
mv $js internal/www/public/scripts/app.$sum.js
